version: '3.3'

services:
  node:
    build: ./
    links:
      - mongo
    ports:
      - "9000:8000"

  mongo:
    image: mvertes/alpine-mongo:3.4.10-0
    volumes:
      - mongo:/data/db
    ports:
      - 27017

volumes:
  mongo:
    driver: local
